import { z } from 'zod';

// Schema for a single item in the list
const ListItemSchema = z.object({
  id: z.string().uuid(),
  content: z.string().min(1, { message: "Content cannot be empty" }),
  completed: z.boolean().default(false),
});

// Schema for the main list object
export const ListSchema = z.object({
  id: z.string().uuid(),
  title: z.string().min(1, { message: "Title cannot be empty" }),
  items: z.array(ListItemSchema).default([]),
  createdAt: z.date(),
  updatedAt: z.date(),
});

// Schema for creating a new list (omitting fields generated by the server)
export const CreateListSchema = ListSchema.pick({ title: true });

// Schema for updating a list (all fields optional)
export const UpdateListSchema = CreateListSchema.partial();

// Schema for URL params containing an ID
export const ParamsSchema = z.object({
  id: z.string(), // Mongoose IDs are strings
});

// Infer the TypeScript types directly from the Zod schemas
export type IListItem = z.infer<typeof ListItemSchema>;
export type IList = z.infer<typeof ListSchema>;
export type ParamsInput = z.infer<typeof ParamsSchema>;